### ISSUE TITLE
Handle Hard drive being off line. Maybe a Transfer max per night

### ISSUE THREAD

**Issue by GrokSoft** [GrokSoft/ELS#38]
If a Hard Drive in the system goes offline for whatever reason. ELS would try and replace all the files that are on the offline drive.
Since ELS is automated, it could use all the data you have for the month.

Maybe we can have a limit to how much it will transfer in one session.
If the limit gets hit - email the admin.

**Comment by Corionis** [comment]
If a storage location defined in the JSON files is missing ELS will fail with an exception. This is not an issue.
